import { prisma } from '@/lib/db'
import { formatDistanceToNow } from 'date-fns'
import Link from 'next/link'

const STATUS_COLORS: Record<string, string> = {
  verified: 'bg-emerald-900/40 text-emerald-300',
  rejected: 'bg-red-900/40 text-red-400',
}

const STATUS_LABELS: Record<string, string> = {
  verified: 'genuine',
  rejected: 'synthetic',
}

function ScoreBadge({ score }: { score: number | null }) {
  if (score === null) return <span className="text-ale-muted">—</span>
  const color = score >= 70 ? 'text-ale-real' : score >= 40 ? 'text-ale-mixed' : 'text-ale-skunked'
  const label = score >= 70 ? 'Pure ALE' : score >= 40 ? 'Mixed' : 'Skunked'
  return (
    <span className={`font-bold tabular-nums ${color}`}>
      {Math.round(score)}%{' '}
      <span className="font-normal italic text-xs">{label}</span>
    </span>
  )
}

function truncate(url: string, n = 52) {
  try {
    const { hostname, pathname } = new URL(url)
    const short = hostname.replace('www.', '') + pathname
    return short.length > n ? short.slice(0, n) + '…' : short
  } catch {
    return url.length > n ? url.slice(0, n) + '…' : url
  }
}

export default async function ScansPage() {
  const scans = await prisma.analysis.findMany({
    orderBy: { createdAt: 'desc' },
    take: 100,
    include: {
      queueItems: {
        where: { status: { in: ['verified', 'rejected'] } },
        orderBy: { updatedAt: 'desc' },
        take: 1,
      },
    },
  })

  return (
    <div className="min-h-screen bg-ale-bg">
      <header className="border-b border-ale-border bg-ale-card px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <img
            src="/ale-icon.png"
            alt="ALE"
            width={36}
            height={36}
            className="rounded"
            style={{ filter: 'drop-shadow(0 0 8px rgba(232, 160, 32, 0.5))' }}
          />
          <div>
            <h1 className="text-2xl font-bold tracking-widest text-ale-amber">ALE</h1>
            <p className="text-xs text-ale-muted italic">Authenticity Logic Engine</p>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8 space-y-6">
        <div>
          <h2 className="text-lg font-bold text-ale-amber">Public Scan Feed</h2>
          <p className="text-xs text-ale-muted mt-1">
            Every URL analyzed by the ALE extension. Scores are generated by Hive AI's deepfake and
            synthetic content detection model. Items marked{' '}
            <span className="text-emerald-300">genuine</span> have been reviewed by a brewmaster.
          </p>
        </div>

        {scans.length === 0 ? (
          <div className="bg-ale-card border border-ale-border rounded-lg px-5 py-16 text-center text-ale-muted italic text-sm">
            No scans yet. Install the ALE extension and analyze a video to see results here.
          </div>
        ) : (
          <div className="bg-ale-card border border-ale-border rounded-lg overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-ale-border text-ale-muted text-xs uppercase tracking-wider">
                  <th className="text-left px-4 py-3">URL</th>
                  <th className="text-left px-4 py-3">Score</th>
                  <th className="text-left px-4 py-3">AI</th>
                  <th className="text-left px-4 py-3">Deepfake</th>
                  <th className="text-left px-4 py-3">Verification</th>
                  <th className="text-left px-4 py-3">Notes</th>
                  <th className="text-left px-4 py-3">Scanned</th>
                </tr>
              </thead>
              <tbody>
                {scans.map((scan) => {
                  const details = (scan.rawResult as any)?.details ?? {}
                  const review  = scan.queueItems[0] ?? null
                  return (
                    <tr key={scan.id} className="border-b border-ale-border last:border-0 hover:bg-ale-amber/5 transition-colors">
                      <td className="px-4 py-3 max-w-xs">
                        <a
                          href={scan.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-ale-amber hover:text-ale-gold underline underline-offset-2"
                          title={scan.url}
                        >
                          {truncate(scan.url)}
                        </a>
                      </td>
                      <td className="px-4 py-3">
                        <ScoreBadge score={scan.realityScore} />
                      </td>
                      <td className="px-4 py-3 text-ale-muted tabular-nums text-xs">
                        {details.ai_generated != null
                          ? `${Math.round(details.ai_generated * 100)}%`
                          : '—'}
                      </td>
                      <td className="px-4 py-3 text-ale-muted tabular-nums text-xs">
                        {details.deepfake != null
                          ? `${Math.round(details.deepfake * 100)}%`
                          : '—'}
                      </td>
                      <td className="px-4 py-3">
                        {review ? (
                          <span className={`text-xs px-2 py-0.5 rounded-full ${STATUS_COLORS[review.status] ?? ''}`}>
                            {STATUS_LABELS[review.status] ?? review.status}
                          </span>
                        ) : (
                          <span className="text-ale-muted text-xs">—</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-ale-muted text-xs max-w-[180px]">
                        {review?.notes
                          ? <span title={review.notes}>{truncate(review.notes, 40)}</span>
                          : '—'}
                      </td>
                      <td className="px-4 py-3 text-ale-muted text-xs whitespace-nowrap">
                        {formatDistanceToNow(new Date(scan.createdAt), { addSuffix: true })}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </main>
    </div>
  )
}
